EXPERIMENT: "Mammals1ExonNP"
TREE: data/trees/rootedtree.OrthoMam.nhx
MUTATION_RATE_PER_GENERATION: 1.0
PROFILE: data/preferences/np.prefs
NUC_MATRIX: data/matrices/nuc_matrix_Simiiformes_MF.tsv
PRECISION_MATRIX:
  fast: data/matrices/precision_half.tsv
  change: data//matrices/precision_one.tsv
  slow: data/matrices/precision_twice.tsv
EXON_SIZE: 498
NBR_EXON: 1
SEED: 42
ALPHA_ARRAY_MIN: 0.1
ALPHA_ARRAY_MAX: 10
ALPHA_ARRAY_STEPS: 20
REPLICATES: 1