MODELS: [MF, MG]
TREE: data/trees/rootedtree.Primates.nhx
MUTATION_RATE_PER_GENERATION: 1.0
PROFILE: data/preferences/np.prefs
EXON_SIZE: 498
NBR_EXON: 10
SEED: 42
ALPHA_ARRAY_MIN: 2
ALPHA_ARRAY_MAX: 2
ALPHA_ARRAY_STEPS: 1
NUC_MATRIX: data/matrices/nuc_matrix_Simiiformes_MF.tsv
REPLICATES: 100
